### ISSUE TITLE
Issue #3 - No .tex File

### ISSUE THREAD

**Issue by martin-gandur** [pos5737/hw01-Daehong-Kim#3]
I couldn't find the `.tex` file that was compiled as your [.pdf]( https://github.com/pos5737/hw01-Daehong-Kim/blob/master/DoSomethingInteresting.pdf).
It seems that you wrote it, but maybe forgot to upload it to GitHub? Or maybe you have it outside of the local folder you synchronized with GitHub through GitDesktop.
_Try to compile your .tex file again and save it in the local folder you have connected to your repository. When you're writing it (before compiling it into the .pdf), try to keep in mind the suggestions made in [issue #1](https://github.com/pos5737/hw01-Daehong-Kim/issues/2) regarding what you can write in your .tex file._

**Comment by DaeKimFSU** [comment]
I added the tex file.
Thank you
